[supabase]
url = "https://tcdzceodgsftvfdczjpt.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRjZHpjZW9kZ3NmdHZmZGN6anB0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2Njc2NTgsImV4cCI6MjA2MDI0MzY1OH0.oswN3Dxaqxd76jCLj5z6SL_toB0YHMgau5mnzZCRnhE"